version: '3'

services:
    flask-app:
        container_name: flask-app
        build: ./
        restart: always
        links:
            - mysql-db
        ports:
            - '5000:5000'
        volumes:
            - ./app:/app
        networks:
            - backend
        depends_on:
            - mysql-db

    mysql-db:
        container_name: mysql-db
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - '3308:3306'
        command: --init-file /data/application/init.sql
        volumes:
            - ./init.sql:/data/application/init.sql
            - ./database:/var/lib/mysql
        networks:
            - backend
    haproxy:
        image: haproxy:1.6
        volumes:
            - ./haproxy:/haproxy-override
            - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        links:
            - weba
            - webb
            - webc
        ports:
            - "8888:80"
            - "70:70" 
    weba:
        build: ./frontend
        expose:
            - 80

    webb:
        build: ./frontend
        expose:
            - 80
  
    webc:
        build: ./frontend
        expose:
            - 80
networks:
    backend:

volumes:
    app:
    database:
